### ISSUE TITLE
Error: Plan Undefined (Firefox/IE) when using Pricing on a form with add-ons

### ISSUE THREAD

**Issue by samizdat808** [recurly/recurly-js#158]
Firefox and IE 9 throw a TypeError: Plan Undefined error when the recurly.Pricing object is attached to a form that contains both a plan and add-ons.

The error is thrown at line 4482 of recurly.js

Using Firebug and putting it into 'break on all exceptions' mode, I noticed that by the time the exception was thrown self.items.plan had a valid value. However, at the time of assignment, it's undefined and stores the undefined value into the plan variable.

I was also able to verify that placing the code in the each block into a setTimeout function of 100ms would result in plan getting the proper value from self.items.plan.

Chrome and Safari are unaffected, but the error does completely break our recurly implementation in FF and IE.

**Comment by floernoult** [comment]
Hi,
Do you have any update on this issue? I'm facing the same issue, and it seems to be still broken. Would you have any workaround to fix this while you are still looking into it?
Thank you for any update on this.

**Comment by chrissrogers** [comment]
@floernoult thanks for finding this. The observer feature was on hold while we added other core features and bug fixes, but I think now is the time. I don't have a workaround at this time. The `setTimeout` workaround mentioned by Mark above seems effective, but I am not comfortable adding that as a permanent fix.

Can you give an example form that will reproduce the issue for you? That will speed up the diagnosis and fix process considerably.

Thanks!

**Comment by floernoult** [comment]
@chrissrogers indeed, the setTimeout workaround works, and I'm using it currently. But of course, this does not seems to be a robust solution, setting a timeout of 100ms being arbitrary, it might not be always working (in my case, 100ms is not enough sometimes). An observer would be a far better solution.

I don't have an example form right now, but I believe any form displaying add-ons and attached to recurly.Pricing would reproduce this issue on Firefox (probably on IE but I've not tested). 

If you can't reproduce let me know, I'll try to build this example for you.

Thanks.

**Comment by nerrad** [comment]
Any update on this?  I'm facing this too in our implementation of recurly.  Any chance of adding the setTimeout as a fix until #140 gets done (which seems to have stalled?)

**Comment by chrissrogers** [comment]
Since it's time-dependent and not 100% reliable, we can't really add it to the trunk. I am able to spend some more time on this though, and will come close on a completion of the observer feature soon. If you are comfortable with the workaround, and need an immediate solution, then I recommend going with the setTimeout impl.

**Comment by chrissrogers** [comment]
Looking through this again, I think I misunderstood the issue initially. An observer won't necessarily be of benefit here, as it's more concerned with reacting to DOM changes than it is to ensuring proper order when applying addons. The issue is simply that one cannot set addons without verifying that they can be used on a plan. Since plan detail retrieval is asynchronous, the application of addons must wait for the plan to be available. I think that clarifies the fix here considerably.

**Comment by chrissrogers** [comment]
Assuming I understand the issue as stemming from the following sort of html structure for the attachment:

```html
<form>
  <input type="hidden" data-recurly="plan" value="basic">
  <input type="text" data-recurly="addon" data-recurly-addon="addon1" value="0">
</form>
```
