### ISSUE TITLE
How to interrupt previous Pricing API call with promise?

### ISSUE THREAD

**Issue by thbar** [recurly/recurly-js#164]
Is there a documented way to interrupt a previous [Pricing API call](https://docs.recurly.com/js/#pricing-api)?

Imagine I monitor changes to a form using KnockOut.js or jQuery, and issue Pricing API calls when the country, plan or vat number changes.

If the user clicks around, this will translate into multiple Pricing API calls.

It would be nice to be able to interrupt the previous calls in order to avoid concurrency issues here (eg: first promise calls done after the second promise is started).

How can this be achieved?

**Comment by thbar** [comment]
That would work for me :-) This is definitely interesting to have this covered inside Recurly.js directly, because otherwise the onus is on the caller to keep track of what has been done and in which order etc. Thanks for considering this!

**Comment by chrissrogers** [comment]
Since we're continuing to rely broadly on Promises internally and as part of our external Pricing APIs, I think the goal should be to comply as closely to the Promise standard as possible -- cancelation isn't a high priority given the downstream dependencies of subsequent calls, specifically in Calculation classes. We'd need to closely consider the side-effects of cancelation, and I don't think that's hugely important given the increased API speeds since this req was made. Any feedback on this call is of course appreciated!
