### ISSUE TITLE
Single use coupons are included in `discount_next` calculation

### ISSUE THREAD

**Issue by whiteotter** [recurly/recurly-js#167]
when really they should only be included in the discount_now calculation

**Comment by snodgrass23** [comment]
For clarification, the `discountNext` calculation assumes all coupons are equal and doesn't check to see if it is a one time coupon and shouldn't be applied to the estimate for the next invoice. This doesn't affect the actual coupon's use since the actual application is done on the Recurly servers and not in this library, which is only serving to provide an estimate.

**Comment by snodgrass23** [comment]
The fix had been merged into the master branch and will be present in the next release.
