### ISSUE TITLE
How to set the pricing API timeout?

### ISSUE THREAD

**Issue by thbar** [recurly/recurly-js#172]
While doing offline work, I noticed that it took exactly 60 seconds for the `catch` function to be called by the Pricing module. I grepped the recurly-js source code and found the `60000` timeout.

It doesn't look like `Recurly.prototype.configure` support passing this as a value. Is there another way currently, or is that something that could be included into the library?

Thanks!

**Comment by thbar** [comment]
Forgot to add: it looks like `recurly.config.timeout = 5000` will work, but I'm not sure if there are side-effects to calling this that way.

**Comment by chrissrogers** [comment]
Yeah, this feature is undocumented since it isn't the mos graceful method of timing out around jsonp. If you're using our xhr+cors request routines, it is much more graceful. You can simply pass a `timeout` property into `recurly.configure` and it will be added to the config object. You shouldn't expect any side effects.

Here are the request routines that use the timeout: [xhr](https://github.com/recurly/recurly-js/blob/master/lib/recurly.js#L175), [jsonp](https://github.com/recurly/recurly-js/blob/master/lib/recurly.js#L223)

Once we switch over entirely to xhr+cors, we will expose this in the docs, as I will be morecomfortable with the timeout procedure.

**Comment by thbar** [comment]
Thanks for the clarification!
