### ISSUE TITLE
GET call to /token API on recurly v3

### ISSUE THREAD

**Issue by rwyland** [recurly/recurly-js#189]
We have implemented the latest recurly v3 in our web application and noticed the following.  Once you call the ```recurly.token()``` API with the form, the POST method is actually performing a GET which exposes the form fields in the URL.  Ideally this information should be contained in the body of a POST method.

Here is the network call in action:
```
Remote Address:64.74.141.63:443
Request URL:https://api.recurly.com/js/v1/token?first_name=First&last_name=Last&phone=%2B1%20(234)%20222-4242&number=4111111111111111&month=12&year=16&cvv=123&address1=Street&address2=&city=City&state=&postal_code=12345&country=US&token=&version=3.0.10&key=sjc-dMDzcqec0BmNflrpPiddc3&callback=__jp0
Request Method:GET
Status Code:200 OK
```

However the src seems to correctly ask for a POST:
```
  this.request('post', '/token', input, function (err, res) {
    if (err) return done(err);
    if (data.fields.token && res.id) {
      data.fields.token.value = res.id;
    }
    done(null, res);
  });
```

Is this functioning as designed? Thanks

**Comment by cgerrior** [comment]
Hi @rwyland,

Did you configure Recurly.js to use XHR+CORS as described [here](https://github.com/recurly/recurly-js#xhrcors)? Once you do that, your HTTP request should automatically become a POST.

-Charlie (Recurly Sales Engineer)

**Comment by chrissrogers** [comment]
> Is this functioning as designed?

This is intentional. The default jsonp transmission method only supports GET requests. This exposes card information in the url, but rest assured that the GET parameters are safely encrypted over SSL.

As @cgerrior mentioned, you may indeed enable XHR+CORS to move those params to the request body. The only caveat is that IE9 will restrict your page to loading over https make the requests.

**Comment by rwyland** [comment]
Thanks guys. 

Any ideas when CORS won't be a Beta feature anymore? Using a "Beta" feature in our production application scares our management. It should probably also get added to the official documentation on your site. 

@chrissrogers This issue of having the form submitted as URL params was brought to our attention by a security scan team. They marked this as a SEVERE issue (actually they made 4 separate tickets out of it); in their minds the only resolution is not doing it. Thanks

**Comment by chrissrogers** [comment]
I can understand why they would be concerned with sensitive params in urls, specifically around server logs, which tend to record the request url quite frequently; however, we can assure that our process for transmitting cardholder data is indeed secure.

From the standpoint of a request made over SSL, as all of our Recurly.js requests are, params transmitted in the URL are just as secure as those transmitted in the body.

[This article](http://blog.httpwatch.com/2009/02/20/how-secure-are-query-strings-over-https/) covers the topic in depth, and highlights cautions which each do not apply to the way that Recurly.js makes requests. There are no subsequent requests with referrer headers, the requests are not entered into browser history, and our servers are handling the requests with such requests specifically in mind.

That said, I completely understand the desire to pass an audit flag. I cannot provide a timeline on the primacy of XHR+CORS transmission, but I can vouch for its efficacy -- we have a few very large customers using that method in production. The major reason we have yet to make it the default is around the IE9 development caveat.

**Comment by rwyland** [comment]
Thanks for the info, appreciate the details.

**Comment by a13xb** [comment]
@chrissrogers

Not directly related to `recurly-js`, but we have run into the same issue with iOS SDK (security audit flagged exposing form fields of the `/token` calls in the URL). The problem with the iOS HTTP framework is that its caching mechanism uses URL as a key, which ends up in the cache database regardless of caching policies, so all the sensitive details end up leaking with cache _keys_, even if the responses are not there.

After some testing it seems that sending a POST request with a JSON payload instead of a GET request actually works just as well. Now, even if my iOS SDK patch is not accepted, I have no problem using a private fork, but none of this is documented. Will I be in a world of pain down the road if rely on this behaviour?

**Comment by chrissrogers** [comment]
@a13xb You likely will not be in a world of pain. I can't make any guarantees, but we do plan to support POST requests on that endpoint for the lifetime of Recurly.js v4 and the iOS SDK. The endpoint will not be documented publicly since it is technically an internal-use endpoint, but our policy for ongoing updates to the endpoint is to make no breaking changes.

**Comment by a13xb** [comment]
@chrissrogers So, let me clarify: is the current behaviour correct, supported for the lifetime of v4 API, and is reasonable to rely on: you can send a POST request with JSON payload with exact same key names and Content-Type set to `application/json` instead of a GET request with arguments encoded in a query string.

As a side note, I think it's a mistake to keep these as internal and undocumented since it makes you rely on official libraries, some of which are barely maintained, if maintained at all (e.g. iOS that wasn't updated for more than a year).

**Comment by chrissrogers** [comment]
Yep, it is reasonable to rely upon a POST request with parameters in the body in the same manner as a GET request with parameters in the querystring. POST requests via XHR are the default method utilized by Recurly.js v4 and will continue to be for the foreseeable future.

Thanks for the feedback on the API, it is 100% appreciated and noted 👍
