### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by Psykar** [recurly/recurly-js#227]
There's an NPM package (https://www.npmjs.com/package/recurly.js) which may or may not be official (?)
It installs just fine, but because you have dependencies manually under components/ requiring it fails.

Any chance of updating the package.json so this can be used correctly from npmjs?

**Comment by chrissrogers** [comment]
That is an unofficial distribution -- the publisher is not authorized by Recurly. I recommend only depending on Recurly.js from our CDN directly -- this will ensure you always have the latest version, and will bolster your security by trusting our source instead of your own packages.

Most importantly, we are likely to introduce breaking API changes in the future that old versions may not support. By loading Recurly.js from our CDN, you can be assured that you are always compatible.

**Comment by chrissrogers** [comment]
Closing this as resolved. Please reopen if more is needed, and thanks @Psykar for pointing out that package.
