### ISSUE TITLE
Is recurly v4 BC with recurly v3?

### ISSUE THREAD

**Issue by romainneutron** [recurly/recurly-js#237]
Hello,

This is a question: Is the version 4 fully backward compatible with version 3?

ie: could I switch from version 3 to 4 closing my eyes, or should I check some changes (did not find them in the changelog)

**Comment by Taytay** [comment]
I have the same question actually.

**Comment by bhelx** [comment]
The short answer is no. That's why we have the major version bump. v4 now uses `Hosted Fields` which means that the sensitive input fields are actually small iframes that are hosted on our servers. This makes things more secure and will also save you some PCI paperwork but as you might be able to imagine, the API for interacting with these iframes is a little different. I'll leave @chrissrogers to correct me or field any more detailed questions.

Perhaps this should be more clear in the documentation or we should have some kind of guide for upgrading from v3.

Please feel free to re-open if you aren't satisfied with the answer.

**Comment by apotek** [comment]
Logged a documentation/feature request for v3 versus v4 as a separate issue: https://github.com/recurly/recurly-js/issues/242

**Comment by bhelx** [comment]
Thanks @apotek

**Comment by romainneutron** [comment]
A migration guide would be appreciated, sure !
Thanks!
