### ISSUE TITLE
Is it possible to programmatically focus field in iframe?

### ISSUE THREAD

**Issue by vojtech-dobes** [recurly/recurly-js#240]
Currently also `<label>` doesn't cause the field to focus. Is there way how to enable that? It's nice from user perspective :).

**Comment by chrissrogers** [comment]
Good suggestion, no there is not a way to force focus at this time. In certain browsers, calling the [focus method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) on an iframe will automatically focus into the first focusable element within the iframe -- in this case the input element.

I will also designate this a feature request. I think it would be useful to pass focus calls from the container divs down to the input elements in the iframe.

**Comment by vojtech-dobes** [comment]
Thanks for your answer, looking forward to it :).

**Comment by smazurov** [comment]
Looking at the PR, I do not see any functionality related to programmatically focusing an element. It appears it looks for labels that are targeting a specific field, and binds a focus event in case a click event is triggered.

My use case is simple, if a user enters a month, I want to immediately focus them on the year. 

I can tap into "recurlyState" events, listen to when month is filled out, and then trigger a click on a ghost label (as my form has no labels), so that year gets focused. That seems quite backwards.

**Comment by chrissrogers** [comment]
Hi @smazurov -- The PR is meant to specifically address label-input pairing, and not programmatic focusing as a whole. Setting up the pairing without any additional implementation code was my goal foremost.

I suggest the following for your use case, for now. While it utilizes a message dispatch that isn't documented, I can assure that it is stable. This would work for changing focus when a user has typed two numbers into the month field. Note that the message being sent will only work once we have published the new version that includes the PR attached to this issue.

```js
let lengthWas = 0;
recurly.on('change', function (state) {
  if (state.fields.month.focus) {
    const lengthIs = state.fields.month.length;
    if (lengthWas === 1 && lengthIs === 2) {
      recurly.bus.send('hostedField:year:focus!');
    }
    lengthWas = state.fields.month.length;
  }
});
```

**Comment by smazurov** [comment]
Cool, missed the part where I can use the bus directly, thanks for the pointer. Will wait for new release and implement. Thank you!

**Comment by FGoessler** [comment]
Would be awesome to have this info in the official documentation!

And even better if one could also detect single digit months. Like the user enters "4" instead of "04" -> one can be sure that there's no second digit supposed to come (as opposed to "1" or "2").

**Comment by chrissrogers** [comment]
@FGoessler -- we're currently hard at work on a new API for hosted fields which will allow far easier interaction with the focus-forcing capabilities. I don't have a specific timeline for its release, but it will be available soon. The overarching reason we don't have it as part of our public documentation is because we're not satisfied with the API for it, and are keen to make it much easier before we document the feature.

As for the single digit months: is this for the card hosted field, or the individual expiry fields? It is possible to input a single digit for the month with either, actually.

With the card field, a user can enter `1/` and the field will auto-update to `01/`, and if the user enters `4`, the field will auto-update to `04/`.

With the individual fields, the user can enter `1` or `4` and does not need to enter a leading zero -- the input will be considered valid. To hint at this, we recommend changing the placeholder value to '1'. The field will not auto-update to add the leading zero, but we can certainly consider a feature request for this.

Hope this is all helpful!
