### ISSUE TITLE
Provide documentation on API differences between v3 and v4, and how to upgrade

### ISSUE THREAD

**Issue by apotek** [recurly/recurly-js#242]
Following up on this question and discussion: https://github.com/recurly/recurly-js/issues/237#issuecomment-199426681

@bhelx wrote:

> Perhaps this should be more clear in the documentation or we should have some kind of guide for upgrading from v3.

So this is a documentation/feature request for such a document.

**Comment by milton-aa** [comment]
any update please? For existing customers this is badly missing. 😭

**Comment by athain** [comment]
Recurley.js v4 is very important because it reduces PCI compliance from SAQ-EP down to SAQ-A., making huge reduction in compliance costs. The Iframes and redirects in recurly.js v3 are not secure enough. We need recurly.js v4 asap.

**Comment by chrissrogers** [comment]
@athain yes please do use Recurly.js v4 -- it is available for general use and is documented here: https://dev.recurly.com/docs/recurlyjs

**Comment by athain** [comment]
Thank you Christopher,

I’m running Recurly.js v3 on my Drupal 7 devsite, using  drupal.org/project/Recurly. It works great, but PCI compliance is keeping me out of production.

I set up Drupal/Recurly on my own in a couple hours, but based on what I think I see, my skills aren’t enough to manage the transition from v3 to v4 in a Drupal environment.

It’s not simply a matter of replacing the .js and .php files with the new ones in github is it?

Aaron

**Comment by colans** [comment]
I opened a support ticket with Recurly to provide this documentation.  I recommend that everyone else do the same.  If enough of us raise it as an issue, hopefully it'll get prioritized.

**Comment by chrissrogers** [comment]
> It’s not simply a matter of replacing the .js and .php files with the new ones in github is it?

The php integration should be okay, since it would just be sending tokens along.

The js integration would need to be updated, specifically to update the styles of the hosted fields to mimic those of your other input fields. Those are the most significant changes between v3 and v4.

**Comment by IanVS** [comment]
This is an old issue, I realize, but I'm just now taking a look at switching from v3 to v4, and I'm kind of surprised that there is no upgrade guide or list of breaking changes.  Is it really only styling that I need to worry about?

**Comment by chrissrogers** [comment]
@IanVS essentially, yes. Be sure to read through the [getting started](https://dev.recurly.com/docs/recurly-js-getting-started) and [styling](https://dev.recurly.com/docs/recurly-js-getting-started) sections of the docs for the most significant changes.

Including the default stylesheet will help make the hosted fields appear close to a normal input, and should make the upgrade process smooth.

You'll need to modify your form markup to remove credit card inputs (number, exp month, exp year, and cvv) and replace them with container elements. Something like the following, illustrated in its simplest form:

#### v3
```html
<input data-recurly="number">
<input data-recurly="month">
<input data-recurly="year">
<input data-recurly="cvv">
```

#### v4
```html
<div data-recurly="number"></div>
<div data-recurly="month"></div>
<div data-recurly="year"></div>
<div data-recurly="cvv"></div>
```

When you call `recurly.configure`, you can pass in additional style properties that pertIn to the internal styling of the hosted field input (font appearance, some padding, etc).

I'd suggest checking out the combined card field first, since it is the simplest integration and includes some additional UX niceties. Feel free to drop any questions you have about the upgrade process here. Glad to help folks move to v4!
