### ISSUE TITLE
V4 does not work when month and year fields are <select> items

### ISSUE THREAD

**Issue by floernoult** [recurly/recurly-js#256]
We just tried to migrate from v3 to v4, and it seems that the recurly.configure() method is throwing an exception in our case. We keep getting the following error: 

`recurly.js?compile=false:4340 Uncaught not-configured: Not configured. You must first call recurly.configure(). (need help? https://docs.recurly.com/js#identify-your-site)`

due to this error thrown:

`TypeError: Cannot read property 'children' of undefined(…)`

After digging a bit, I realized that we are using selects for the month and year fields of the credit card information, and replacing them by inputs solves this issue:
`<input id="month"
            data-recurly="month"
            maxlength="2"
            placeholder="mm"
            type="text"
            required>`

Is it possible that select elements are not correctly handled by RecurlyJS v4?

Thanks,
Florian

**Comment by chrissrogers** [comment]
Unfortunately it's not possible to use a select field. v4 injects iframes into your payment page's card fields (including expiration month and year) in order to isolate customer card data from your payment page. This limits the fields to normal text inputs, since select fields are not feasible within an iframe.

Instead of using a select field though, I recommend a normal `<div>` element that you style to look like an input field.
