### ISSUE TITLE
Include appropriate currency separator for prices over $999 USD

### ISSUE THREAD

**Issue by MichaelFromin** [recurly/recurly-js#261]
When using Recurly.js for prices over $999.00 USD I get this:

![screen shot 2016-06-02 at 8 15 26 am](https://cloud.githubusercontent.com/assets/12281396/15747953/3479b9d4-289a-11e6-834f-3f00285b20a5.png)

note that the plan price is missing a comma.  What do I need to do in Recurly.js to get the `total_now` field to use the appropriate separator in the price?

The HTML I am using to get the price into the page is as follows:

```
<h2 id="totalPrice">
  Plan Price:&nbsp;&nbsp;
  <span class="priceData" data-recurly="currency_symbol"></span>
  <span class="priceData" id="total_price" data-recurly="total_now"></span>
</h2>
```

**Comment by chrissrogers** [comment]
To modify the appearance of a pricing output, you'll need to listen to the `change` event and parse it from there.

```js
pricing.on('change', (price) => {
  let planPriceDisplay = parseFloat(price.base.plan.unit).toLocaleString();
  // and so on...
});
```

Note that you may want to use something other than [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) since IE only added support in version 11.
