### ISSUE TITLE
Testing with WebDriver, but trouble with PhantomJsDriver

### ISSUE THREAD

**Issue by kerrykimbrough** [recurly/recurly-js#274]
I wondering if I'm missing something simple, because it seems like the tests for recurly.js might be doing something like this with more success.

I have a test page that uses https://js.recurly.com/v4/recurly.js and contains a form structured like the standard example. And I have a program that uses Selenium WebDriver to complete and submit the form to get a billing token. (The billing token is extracted by getting the resulting ```value``` attribute of ```<input type="hidden" name="recurly-token" data-recurly="token"/>```) This program works fine when the browser is Chrome, but it fails when the browser is PhantomJS: the ```recurly.token``` callback gets an ```err``` object like this:

```
{code=validation, name=validation, message=There was an error validating your request., fields=[number, month, year, cvv]}
```

Which is baffling, because my success running the exact same program with Chrome tells me that all of these fields have been filled in correctly.

FWIW, the program is reading the test page from a local file, and the PhantomJS setting for ```localToRemoteUrlAccessEnabled``` is true.

**Comment by chrissrogers** [comment]
My familiarity with webdriver isn't superb, and our internal test suite stubs out the response from the fields to meet the API standards of the field communications. Thus they respond with field values expected and set up by each test.

Since I don't have a quick answer for you, I would suggest setting up a debug environment in PhantomJS to see when the failure in the flow occurs. Are the fields receiving the values? Are the fields reporting the values correctly? Is Phantom waiting for the fields to load? etc.

**Comment by jfitisoff** [comment]
FWIW, I've always had problems with Phantom.js in general. Every time I've
tried it, some things would work great but then I'd run into places where
it just couldn't handle something that a real browser had no problems with.
I keep trying because I like the idea of it, but have never had much luck
and have always gone back to a real browser.

An alternative approach would be to run a real browser headlessly, using
Xvfb. A lot of CI services support this out of the box. We're doing this at
work for our functional tests and I have a personal project running this
way in CircleCi. People worry about the speed but there isn't a whole lot
of difference and real browsers are much more reliable.
