### ISSUE TITLE
Allow first_name and last_name as text input

### ISSUE THREAD

**Issue by joneslloyd** [recurly/recurly-js#308]
Hi there,

I'm getting to grips with recurly.js, and I'm finding that it's not injecting the iframe for `first_name` and `last_name` fields, when I use an `input` of `type="text"` (rather than a `div`).

Here's an example of my `first_name` field:
```
<input type="text" data-recurly="first_name" name="input_2.3" id="input_1_2_3" value="" aria-label="First name" tabindex="31" aria-required="true" aria-invalid="false">
```

(Using `input` is a requirement for me, as I'm integrating Recurly with Gravity Forms)

Thanks for any help in advance!

**Comment by chrissrogers** [comment]
@joneslloyd only credit card fields will have iframes injected: number, month, year, and cvv. All others are left as normal inputs, since they are not subject to PCI security standards.

We cannot inject the iframes into input fields unfortunately, as they are not container elements. Are you trying to make them look a certain way? If so, the styling section of the documentation will give you all the information needed to make the iframes appear just like the rest of your input fields.

**Comment by joneslloyd** [comment]
@chrissrogers Ahh got it! That's good to know -- I was worried that something was going wrong.

It does seem to be injecting the iframes into my input fields as far as I can see:
![screen shot 2017-01-12 at 10 45 56](https://cloud.githubusercontent.com/assets/997427/21884623/5ca7c53e-d8b4-11e6-83d4-6a878576cc38.png)
(Which is perfect for me, as I can't control the field types that are generated)
