### ISSUE TITLE
Error in iFrame?

### ISSUE THREAD

**Issue by AnaCampoVe** [recurly/recurly-js#310]
Hi Team!!! 

Today we have realized that Credit card fields that you have in your iFrame, and we have inserted in  our webpage, are getting crazy. Tab doesn't work, fields content overlaps... Do you have news about any problem of this kind?? This is a really urgent issues, as our customers can't subscribe to Recurly.

Regards,

Ana Campo

**Comment by bennadel** [comment]
Yes, we are getting this also!!! Looking at the source, it looks like the IFrame suddenly contains **3 inputs**:

[iframe](https://www.screencast.com/t/1J1DbBBS)

This is super urgent!

**Comment by bennadel** [comment]
I have opened an urgent ticket with their support.

**Comment by AnaCampoVe** [comment]
Thanks bennadel!!! We have also an opened ticket with them!! Let's see if this issue is solved as soon as possible.

**Comment by quinne-anderson** [comment]
Perfect!!! Stand by for updates from Rachel's team. Have a great weekend!

**Comment by bennadel** [comment]
We upgraded our version of the Recurly.js library from `v4.0.4` to `v4.3.0`. Apparently, the JS file that was being loaded inside the hosted-field iframes was no longer compatible with the version of the Recurly.js file we were using. Upgrading the lib seems to have fixed the issue.

The documentation suggests loading the Recurly.js lib from their CDN so that they can control both versions of the file. But, we have a build system that bundles all our JS. So, I was pulling the old version down in order to reduce the number of HTTP requests (and possible points of blocking / failure on page load).

**Comment by chrissrogers** [comment]
Closing this issue due to resolution in v4.3.0
