### ISSUE TITLE
Is there a reason the tax estimation always rounds up partial cents?

### ISSUE THREAD

**Issue by boroth** [recurly/recurly-js#312]
In lib/recurly/pricing/calculations.js, the final tax caclulation uses a `taxCeil` function to round up for any partial cents. 

I have an instance where the javascript library shows the subtotal as $349.00, and the tax as $28.80 (in TX with 0.825% sales tax it should be $28.79), but when the subscription is actually processes, it charges the card for the correct amount ($349 + $28.79).

I'm assuming that the reason for using the ceiling function is to avoid situations where the final price charged to the card never exceeds the amount shown through the webform? There are some people in my office worried that the amounts don't match up (although I believe my assumption is true, and possibly some liability protection?)

I'm debating forking the project to make that change on my own, and also wanted to ask if there were other considerations that went into play when making that decision (the comments say something about avoiding floating point calculations).

**Comment by chrissrogers** [comment]
> I'm assuming that the reason for using the ceiling function is to avoid situations where the final price charged to the card never exceeds the amount shown through the webform? There are some people in my office worried that the amounts don't match up (although I believe my assumption is true, and possibly some liability protection?)

That's absolutely correct. It's much better to err on the side of a higher estimate in this case, especially considering the max overestimate is 1 cent. There are certain jurisdictions, either state, county, or local, which do require rounding down, or in some totality of rounding rules do end up rounding down instead of up; however, there are a number that do not. In order to make the tax estimate quickly, we make calculation assumptions around rounding rules. Instead of looking up all the local rules, we simply round up on the cent. The final tax calculation is of course accurate to all localities.

Hope that explains things some!

**Comment by boroth** [comment]
Thanks for the quick response!

**Comment by chrissrogers** [comment]
As for the comments about floats [here](https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/calculations.js#L293-L294), that just referers to the usage of scientific notation numeric conversion in that function.
