### ISSUE TITLE
Feature request: add support for one-time charge coupons

### ISSUE THREAD

**Issue by jchayan** [recurly/recurly-js#319]
Hi, I'm trying to validate coupons on the client-side with recurlyjs, but one thing I note is that it requires mandatory a subscription plan. This makes sense for subscriptions but, what about one-time charge Recurly coupons? Why isn't there an use case that supports pricing on single purchases?

Thanks.

**Comment by chrissrogers** [comment]
Hi @jchayan -- the pricing class is certainly intended for subscription plans first and foremost. You can use `recurly.coupon` to get the details directly without using the Pricing class, if that coupon is redeemable on a plan. This is a stable method that we do not to document due to the superior ease of use of the Pricing class.

We don't currently support one-time payment coupons at this time. So I'll consider this a feature request, and quite a good one at that.

**Comment by jchayan** [comment]
Thank you for the heads-up @chrissrogers

**Comment by chrissrogers** [comment]
This will be coming as part of #399
