### ISSUE TITLE
Automated testing of endpoints that accept Recurly.js tokens

### ISSUE THREAD

**Issue by sebastianhaas** [recurly/recurly-js#365]
From my original support request:
> I was wondering how to write automated tests for the endpoint that is receiving tokens generated by Recurly.js. Obviously, I don't want to launch a web browser for this, so I need a way to mock the functionality Recurly.js is offering. Is there any standard procedure?

As of today, I've realized that there is no way to generate Recurly.js tokens for testing purposes other than using an actual browser. I've [written a small application](https://github.com/tapkey/recurly-js-mock) that is able to carry out all required steps to retrieve a token in the background, suitable for automated testing.

But still, I really think there should be a way to retrieve Recurly.js dummy tokens for testing purposes.

**Comment by chrissrogers** [comment]
Thanks @sebastianhaas -- I've logged a request and we'll consider this. You may wish to make requests to the token endpoint that recurly.js queries in order to generate a token, but I will say that we won't officially support that methodology. Just watch the network tab to see what that request looks like.

Ultimately I suggest using mock responses for external services when testing your application.
