### ISSUE TITLE
React compatible version?

### ISSUE THREAD

**Issue by leebenson** [recurly/recurly-js#372]
Are there any plans to release a React version of Recurly.js?

We run React universally (browser + SSR), and try to avoid libraries that manipulate the DOM or overlay styles after loading.

It would be awesome to have a collection of React components that could be embedded using regular props, rather than relying on DOM injection.

Kinda like how Semantic UI do it with 'off-the-shelf' components would be great -> https://react.semantic-ui.com/introduction

**Comment by chrissrogers** [comment]
We're unfortunately somewhat limited when it comes to reactive UIs, since the hosted fields must be implemented as iframes in order to provide the best level of PCI-compliant card information security. While it's easy for hosted fields to communicate with each other despite load order or DOM position, it takes quite a bit of time (relatively) to load a requisite iframe document and initialize it.. just enough time to make it a noticeable detriment to a reactive UI. So it really exposes the uncanny valley that these hosted fields are limited to.. That said, we're exploring some solutions that may alleviate this somewhat.

Either way, it is possible to use Recurly.js with React as long as you bind the injection to after your component loads, and try to have the DOM reload as infrequently as possible. Hope this information is helpful.

**Comment by leebenson** [comment]
Thanks @chrissrogers, makes sense.

**Comment by curatehealth** [comment]
Any updates on a React version of Recurly.js. @chrissrogers

**Comment by chrissrogers** [comment]
Yes! We are hard at work on a React component. I do not have an exact release date, but an announcement will be forthcoming when it is ready. Recurly.js is undergoing a significant and backwards-compatible architectural shift to support this, which you can see on the [elements branch](https://github.com/recurly/recurly-js/tree/elements) if you like.

**Comment by curatehealth** [comment]
That’s great. How about for react native? @chrissrogers

**Comment by chrissrogers** [comment]
@curatehealth React Native has its own set of constraints, unfortunately. Please see my reply to #521

**Comment by jondavidjohn** [comment]
Any progress on this?  Looks like the last commit on mentioned `elements branch` was some time ago in July.

**Comment by chrissrogers** [comment]
Hi @jondavidjohn -- yes! We are at work on some underlying aspects of React support, including the component itself. The `elements` branch here is a good place to watch, as it's a baseline requirement for the component. While I can't give a specific timeline right now, it's definitely a focus for us.

**Comment by chrissrogers** [comment]
Happy to let all of you know that [react-recurly](https://github.com/recurly/react-recurly) has been made available. Cheers!

[docs here](https://recurly.github.io/react-recurly)
