### ISSUE TITLE
Calculation discrepancy for taxes

### ISSUE THREAD

**Issue by kisaraofpern** [recurly/recurly-js#400]
There appears to be a discrepancy in the behavior of `recurly-js` vs the Recurly API.

In `recurly-js`, there are explicit calls to `Math.ceil` during the calculation of tax:
```
self.price.now.tax = taxCeil(self.price.now.tax);
self.price.next.tax = taxCeil(self.price.next.tax);

[...]

function taxCeil(number) {
  return +(Math.ceil(number + "e+2") + "e-2")
}
```

However, when a call is sent to the Recurly API (e.g., at `/subscriptions/preview`), the response includes a value for `tax_in_cents` that appears to be rounded.

Example calculation: a particular purchase in MA --
```
Subtotal: $69.00
Tax: ($69.00 * 0.0625): $4.3125
```

`recurly-js` will yield $4.32, but the Recurly API will yield $4.31.

**Comment by chrissrogers** [comment]
Hi @kisaraofpern -- yes, you are absolutely correct in your assessment. Due to the very high volume of tax calculations performed in Recurly.js, we can only provide a tax estimate which applies broadly to the largest number of tax locales. Some locales differ in their rounding rules, but the safest way to perform the generic rounding is to ceil the rate subtotal, potentially leading to a 1 cent over-estimate depending on the locale. Our hope is that this behavior is the least disruptive way to broadly provide a tax estimate in a way that is as fast as possible for the end-user.
