### ISSUE TITLE
V4 uses cached environment variable

### ISSUE THREAD

**Issue by mwnachman** [recurly/recurly-js#425]
We are experiencing problems switching from development to staging to production environments because it appears that V4 is getting a CORS error because it is using a cached environment variable in the headers that only refreshes when caching is disabled (ie, when Chrome dev tools is open).  V3 doesn't seem to have this issue, but we are using the payment iframes, so we need V4.  We think this is only going to be a problem for us and our QA people, but we were hoping for some insight as to how to fix it, in case it's not limited to those circumstances.  Thanks!

**Comment by chrissrogers** [comment]
v3 defaults to JSONP for its API communications. If this continues to be an issue for your pattern of switching environments v4, you may wish to switch to JSONP using the following config.

```js
recurly.config({
  cors: false,
  // ...
});
```

If you get the chance to record the headers you're receiving when the error occurs, please post them here.

**Comment by mwnachman** [comment]
Thanks, Chris!  

I think I was imprecise in my question.  The problem is in the initial fetch in the script in the markup.  When we try to use the recurly object on the window, we get an error that recurly is not defined.  It says access to the script at the CDN from origin (eg, staging URL) has been blocked by CORS policy.  The 'Access--Control-Allow-Origin' header has a value of (eg, production URL) that is not equal to the supplied origin.  The staging origin is therefore not allowed access.  We were thinking we could self-host a copy and fall back to it if the initial GET fails, but we would rather do it another way.

Here's the error:

![screen shot 2018-02-02 at 14 15 02](https://user-images.githubusercontent.com/15222281/35750943-b7c95072-0824-11e8-9ae2-7ceb8a5687ad.png)

**Comment by chrissrogers** [comment]
Ah, okay, yes that's a bit different. What is the request being made? It may help to take a screenshot of the rejected request in the chrome network tab. It seems like you may be trying to fetch recurly.js via an XHR request, which is not supported -- it would need to be included in the page using a script tag. Could you also provide the way in which you are including recurly.js on your page?

**Comment by gilhooley** [comment]
Hi Chris, we're including 
`<script src="https://js.recurly.com/v4/recurly.js"></script>` in index.html, which is the source of the error in the screenshot Meredith posted.

**Comment by chrissrogers** [comment]
I'm just now noticing the difference between the ACAO header and origins (subdomain `libra` vs `libra-staging`) I believe this is due to browser cacheing of the request, which is quite aggressive. When switching environments, you will need to clear your browser cache of the recurly.js resource in order to refresh the ACAO header. sorry this isn't more helpful, since it's exactly what you brought up initially.. but I think given the cache behavior we must push out to browsers for peak performance, it is necessary.

One method you may try is to initially load recurly.js in a new tab, which should cache a response without the ACAO header, thus allowing you to switch origins without issue.

**Comment by mwnachman** [comment]
No worries!  Thanks for your help!

**Comment by chrissrogers** [comment]
Cheers! Glad you've brought this to our attention.
