### ISSUE TITLE
Could you please add a config value for Tabindex? 

### ISSUE THREAD

**Issue by omaracrystal** [recurly/recurly-js#430]
I would like to apply tabindex="-1" when the form shouldn't be tabable. I am working with an accordian step form - and could really use the option to set the tabindex attribute. Is this feasible?

**Comment by chrissrogers** [comment]
Interesting, yeah that's certainly a viable use-case for changing the tabindex, and it is feasible to add support for that property.

Are you using the combined card hosted field? And what tabindex value is currently set in the field or fields you are trying to set, if any is present?

**Comment by chrissrogers** [comment]
@omaracrystal one complexity has come up as I've been thinking about this feature.

The card field contains three separate fields. At first my inclination would be to increment each field by one from the provided config value, allowing the developer to assume that the card field will occupy 3 consecutive tabIndex values. I don't love this because the configured value doesn't correlate precisely to the expressed behavior, but it does seem to be the least intrusive. A tabIndex less than zero would not induce the increment.

Any thoughts on this, as to whether it fits your scenario?

**Comment by chrissrogers** [comment]
Just a heads up that this requested change was implemented and was deployed to our CDN today.
