### ISSUE TITLE
v4.6.4: Safari 10.0.1 & Safari 9.1 Complain hosted-field.js is Trying to Access Top Frame

### ISSUE THREAD

**Issue by jorgerdz** [recurly/recurly-js#462]
![image](https://user-images.githubusercontent.com/5052387/40456536-88dc9c94-5eb7-11e8-89d8-ec075e68df74.png)

This seems like a security issue.

How can I prevent this from happening?

**Comment by chrissrogers** [comment]
Thanks for the report -- I have just a few questions to narrow it down some. Does this behavior occur in Safari 11? Is there a particular user or page behavior that consistently triggers this warning?

If it's possible in the Safari console to click the reference to the line of code, the exact line causing it would help a great deal as well.

**Comment by chrissrogers** [comment]
If you have a demonstration link as well that I can check to reproduce the issue, that would help immensely as well. Cheers!

**Comment by jorgerdz** [comment]
@chrissrogers Thanks for the quick response! I appreciate it.

- I have only been able to reproduce in Safari 10.0.1 and 9.1. I have not been able to reproduce in 11 or 10.1, or any other browsers.
- No specific user behavior needed, as soon as the form opens the error is logged.
- Below is the code that gives the error. If I stop execution at that highlighted line, any code evaluated in the console will throw the origin error, which is particularly strange:
![image](https://user-images.githubusercontent.com/5052387/40502235-f770fc48-5f4f-11e8-9cde-6c2f93e01dad.png)

You can replicate it in this site, clicking Pricing -> Choose Plan (you need to sign up for a free account though):
https://placeit.net
![xsfkvpgul2](https://user-images.githubusercontent.com/5052387/40502975-28f3cd7a-5f52-11e8-9d3f-5541d7e46403.gif)

**Comment by chrissrogers** [comment]
From my tests on safari 9 thus far, it appears there is a window reference issue in those browser versions exhibiting the following behavior:

When in the context of an iframe, any reference to the iframe's `window` will trigger the same-origin policy error. The underlying cause of this is not immediately clear, but appears to be universal for `window` references, but does not appear to affect the access to that property, or the properties that our hosted field library requires in order to function.

I am inclined to think that this is a bug in Safari which was ultimately fixed in 10.1..
