### ISSUE TITLE
recurly.token: V4 fails where V3 succeeds with same data

### ISSUE THREAD

**Issue by davidmcl** [recurly/recurly-js#473]
A simple switch to V4 ([script src="https://js.recurly.com/v4/recurly.js"], with no other code changes causes a validation failure when executing the recurly.token function...
```
recurly.token(billInfo, function (err, token) {
	if (err) {
		//... testing
		console.log('recurly.token-billInfo: ', billInfo);
		console.log('recurly.token-err: ', err);
		//
... redacted ...
```
I validate the individual `data-recurly` values before-hand without errors using the `recurly.validate.X` functions.

I can't seem to figure out what the issue is, but I don't think this should fail.

A screen shot ...

![screenshot at 2018-08-28 15-14-26](https://user-images.githubusercontent.com/2047925/44750837-22e8a880-aadc-11e8-912e-a687d30c5d9c.png)

... shows the `billInfo` data input to, and `err` results, from the token call.

Again, all I have to do to "succeed" is to change the script source back to V3.

Let me know if you have any insight or need more information.

BTW, I would think that a little bit more descriptive message than `There was an error validating your request.` would be a good thing. 

Thanks,
David

**Comment by chrissrogers** [comment]
Hi @davidmcl -- great question.

There are a few changes you'll need to make migrating from v3 to v4. The [documentation here](https://dev.recurly.com/docs/recurly-js-getting-started) explains the integration path for v4 in detail, and I will give you a brief of the changes you'll need to make.

Recurly.js v4 introduced the concept of hosted fields. These are a more secure method of capturing customer card data, ensuring that their payment information is never exposed to your site. This is a huge benefit for security and reduced PCI compliance exposure.

First, you will need to update your payment form. The credit card fields `number`, `month`, `year`, and `cvv` will need to be removed and replaced with a container element in the form `<div data-recurly="card"></div>`. I recommend using the card field since it includes a handful of validation and UX improvements, but you can also use separate fields for the number, month, year, and cvv. This is explained more completely in the documentation [here](https://dev.recurly.com/docs/recurly-js-getting-started#section-build-a-card-form).

Your `recurly.token` call will also need to be modified. Instead of passing `billInfo` as you have been, you'll need to pass a reference to your checkout form that contains the hosted fields. Your callback function can stay the same. More info [here](https://dev.recurly.com/docs/recurly-js-getting-a-token).

you'll notice that the hosted fields won't look like the rest of your payment form inputs. That is because they are in fact iframes, and will need to be styled in order to get them to look right. We provide a stylesheet that works as a good baseline for styling the hosted fields to your needs: `<link href="https://js.recurly.com/v4/recurly.css" rel="stylesheet" type="text/css">` will do just fine. To tweak styles further, and to cover styles for when the field is invalid, etc, see the relevant part of the docs [here](https://dev.recurly.com/docs/recurly-js-getting-started).

I hope this helps you with your upgrade path. Please do let me know how I can help further as well. My hope is that you'll really like the card hosted field.

**Comment by davidmcl** [comment]
Thanks for your excellent reply - as far as an great question, I'm afraid I fell victim to the dreaded RTFM syndrome.

I was paying more attention looking at the changes to the api calls, and just blew past the recurly.js change info with a quick glance at the material that I would "get back to later" - the scope of the changes didn't seem to sink into my brain-dead head at the time.

The state object looks interesting - don't recall that before, so I suspect it's new.
 
Regarding the styling, I'll have to send that to the design folks;  I don't do pretty :-)  
I'll try to get some feedback for you regarding their thoughts on the card hosted field.

Thanks,
David

**Comment by chrissrogers** [comment]
Sure thing @davidmcl. While the documentation is a good baseline for creating a new integration with Recurly.js v4, it is not written to highlight the upgrade path from v3, so I totally understand thinking it could be drop in.

I'm keen to hear about your upgrade experience, especially any snags you run into. Cheers and happy upgrading.

**Comment by chrissrogers** [comment]
Running with this a bit, I took the basis of the text above to write out an [upgrade section in the docs](https://dev.recurly.com/docs/recurly-js-upgrading).

I'll close this issue for now, but please do feel free to comment here, as I will still get notifications, or create a new issue as you see fit.

**Comment by raysuelzer** [comment]
It's a real shame that all of this documentation appears to have been moved or removed. I'm reading the v4 documentation right now and it doesn't mention anything about this....

This is what it shows is required. Note that there is absolutely no indication that we need manually configure anything else: https://recurly.com/developers/reference/recurly-js/#the-card-element

```<form id="my-form">
  <input type="text" data-recurly="first_name">
  <input type="text" data-recurly="last_name">

  <div id="recurly-elements">
    <!-- Recurly Elements will be attached here -->
  </div>

  <!-- Recurly.js will update this field automatically -->
  <input type="hidden" name="recurly-token" data-recurly="token">

  <button>submit</button>
</form>
```

Example js from documenation:
```
const elements = recurly.Elements();
const cardElement = elements.CardElement();
cardElement.attach('#recurly-elements');
```
