### ISSUE TITLE
Problems calling configure multiple times

### ISSUE THREAD

**Issue by mramato** [recurly/recurly-js#494]
I have a SPA where navigating to/from our billing page creates/destroys DOM elements as needed.  Each time the page is activated, we call `recurly.configure` to wire everything up.  We recently noticed that if the DOM elements are added and removed quickly, `recurly.configure` can get into a broken state and the end result is a missing/blank form instead of the recurly card widget.  At that point, the only fix is a full page refresh.

I noticed lots of older issues with this problem, and tried a variety of solutions, but couldn't find anything that worked reliably.  Then I stumbled upon `recurly.Recurly` which seems to be an instantiatable class that gives me a separate instance each time.  Creating an instance for my form and throwing it away when the form goes away seems to completely solve my issue and a much cleaner approach to the problem then a global object.  But I can't find anything in the documentation about this class and whether it's meant to be used.  Is this simply a documentation issue, or am I way off the mark in how to solve my problem?

Any help would be greatly appreciated.  Thanks!

**Comment by chrissrogers** [comment]
`recurly.Recurly` is the class used to instantiate the `recurly` singleton, and a cursory take on your use-case makes me think that using it in this way should be fine. It isn't documented because we don't have an official pattern for multiple instantiation at this time. Situations where a problem can occur are if you allow multiple instances to operate simultaneously, i.e. making calls to two separate instances at runtime, since they will ultimately share the same message flow with each other, despite the message only being relevant to one instance. We are in the process of implementing a better pattern here to allow for multiple instantiation and support implementations like yours.

However, since we don't have a completed pattern at this time solidified in documentation, I can't guarantee that a future update won't interfere with an implementation where you're using the `Recurly` class directly. Constructor arguments may change, and a formalized instance destruction routine may be necessary. My hunch is that it shouldn't, but I can't make a guarantee. Sharing any relevant code would help me assess.

You may consider the following: upon calling `recurly.configure`, blocking DOM updates and adding a callback to `recurly.ready` to free the block. The callback is immediately invoked if the instance and hosted fields are finished initializing, or called async once that process has completed. At that time, you'd be safe to call `configure` again and run through the same blocking procedure. It should be a matter of ~150ms depending on the network connection, as the field iframes load. This would be a future-proof approach for the lifetime of v4.

As ever, any feedback on the above is appreciated, and I would be very pleased to know more about your specific needs as we build out the capability to do exactly what you're looking to accomplish.

**Comment by chrissrogers** [comment]
I'd like to share an update on this.

`v4.9.5` introduced a pattern of message isolation to a single instance, and a subsequent deploy of our hosted field application today has activated that message isolation. We are still holding on official patterns as the pattern migration is still in progress, but this is an essential step to supporting your multi-instantiation use-case. In short: messages sent from one instance will isolate to hosted field instances associated with that recurly instance, and hosted field messages sent back will isolate to its concerned recurly instance only.

Since we are still developing this feature, the same cautions as above still apply, but this is an important step and I hope it solidifies your integration some!

We have added a **not-as-yet documented** `recurly.destroy` method which will unbind all listeners and destroy bound hosted fields from a recurly instance, preventing future messages from causing unintended interference and process time. Please feel free to test this functionality in your implementation as follows:

⚠️ **For beta feature testing consideration only** 
```js
// To be called when you intend to no longer use a given Recurly instance
// The guard here is recommended in case the method name changes in the future.
if (recurly.destroy) recurly.destroy();
```
