### ISSUE TITLE
Pricing module does not contain metadata about optional addons

### ISSUE THREAD

**Issue by hasghari** [recurly/recurly-js#516]
I'm using the pricing module by attaching a form to it as such:

```javascript
const pricing = recurly.Pricing();
pricing.attach(document.getElementById('pricing'));
```

I want to be able to dynamically set the addons for the subscription by listening to the `set.plan` event
```javascript
pricing.on('set.plan', function(plan) {
  // plan.addons does not contain info about optional or editable
})
``` 
but the metadata returned for the addons does not contain any information about whether the addon is optional or editable.

How could I accurately display the exact amount the customer will be charged since some addons will be required and not editable?

**Comment by csmb** [comment]
Hello there @hasghari! We're taking a look at this for ya, and will update the thread when we have some info to share. Thanks!

**Comment by chrissrogers** [comment]
Hi @hasghari, thanks very much for the detail you've provided.

We can add the `optional` and `display_quantity` values to the API response so that you will get this information. I don't have an exact timeline for this at the moment, but will update here when I do!

In the meantime, the best option to unblock you would be to store this information in a hash client-side. Something like the following:

```js
ADD_ON_META = {
  my_add_on_code: {
    optional: true,
    display_quantity: true
  },
  // ...
};

pricing.on('set.plan', function(plan) {
  plan.addons.forEach(addOn => {
    // ADD_ON_META[addOn.code].optional
    // ADD_ON_META[addOn.code].display_quantity
  });
});
```

Obviously not the best solution if you have many add-ons, but it will let you achieve the functionality you need until the API updates go out.

**Comment by hasghari** [comment]
I appreciate your attention to this matter. I look forward to API updates. Thanks!

**Comment by chrissrogers** [comment]
Just noting that this was closed by an API update being implemented. It has not been deployed to production as yet, and I will update here when it has. Cheers!

**Comment by chrissrogers** [comment]
I have an update for you! We have updated the endpoint here to include the `optional` and `display_quantity` properties for plans. Please let me know how it works out for you!

**Comment by hasghari** [comment]
Wonderful, works great. Thanks for your help with this.
