### ISSUE TITLE
Paypal frame close event

### ISSUE THREAD

**Issue by pany100** [recurly/recurly-js#520]
Hi there. Is there any event I can listen to, when a user manually closes the paypal dialog? Looked in paypal docs and it says that the `onCancel` callback should handle that, so I tried to listen for `recurly.PayPal` `cancel` events, but no success. Also tried `error` with the same results.
I been digging a bit into the code and found that the Frame is emitting `error` and `token`, but didn't find any `cancel` emit. But may be I missed something (not using braintree)
I am using version 4.9.6.
Thanks in advance

**Comment by chrissrogers** [comment]
Hi @pany100 -- great question! It is possible to receive a cancel notification, but it's a bit limited right now. Here's how it currently works:

- The customer would have to click the following in the paypal express checkout flow:

![](https://cldup.com/w_hbiNLGV3.thumb.png)

You would then be able to listen for the `error` event to capture the occurrence like this:

```js
paypal.on('error', function (error) {
  if (error.cause && error.cause.code === 'paypal-canceled') {
    // react to cancelation
  }
});
```

We can absolutely do better than this, since this doesn't handle the more common scenario of a customer simply closing the window. I think the best solution would be to poll the window for closure (we can't listen for the unload event since these are cross-domain windows) and emit a 'cancel' or 'closed' event accordingly. I'll add this as a feature request and will notify you here of any status updates. And if you're willing to implement this in the `Frame` and `DirectStrategy` classes, I'd happily accept a contrib and prioritize review!

So for now, I'd recommend the above snippet to handle our current limited support, and we'll plan to expand the feature.

**Comment by pany100** [comment]
@chrissrogers as we are already listening to the `error` event, clicking the link cancellation is handled correctly. Thanks for the recommendation anyway. I will be keeping an eye on this so I can implement the solution when this feature is released. 
Thanks for the detailed answer.
