### ISSUE TITLE
Focus Recurly field within iframe

### ISSUE THREAD

**Issue by luciob** [recurly/recurly-js#523]
Hi everyone!
I'm trying to focus a Recurly field hosted within an iframe element.
Doing it the standard way `document.getElementById('recurly-iframe').contentWindow.document` causes obviously Chrome to throw a Cross Origin error. 
I've tried to search for a clean way to do it reading Recurly documentation but didn't find anything about it.
The only barely related thing that I've found out is [this github post](https://github.com/recurly/recurly-js/issues/240) where the thing gets done using `recurly.bus.send('hostedField:year:focus!')` but it didn't worked in my case.
You'll find my code below:

```
<!-- My HTML code -->
<form>
  <input id="user-name-field" ... />
  <div data-recurly="card">
    <!-- Where Recurly iframe gets injected -->
  </div>
</form>
```

```
// My JS code
recurly.configure({
  publicKey: MY_RECURLY_KEY,
  style: {
    all: {
      // Style options
    },
  },
});

const userNameField = document.querySelector('#user-name-field');
userNameField.addEventListener('click', () => {
  // Doing things...
  // Here I'd like to focus Recurly's credit card field
});
```

I've already contacted Recurly support with no luck.
Please let me know if there's a way to do it!

**Comment by chrissrogers** [comment]
Greetings @luciob,

We support cases where you'd like a label interaction to put focus into a hosted field, we do support that by doing the following:

```js
<label for="my-recurly-card">card</label>
<div data-recurly="card" id="my-recurly-card"></div>
```

I think you're really close to what's needed to get your desired result. We don't document the bus message API because it is an internal feature-set, but it is stable. You'll just need to modify the message to `hostedField:card:focus!`. It isn't possible to programatically focus into a specific field within the card field, but if that's desired we can certainly add a feature request.

I've created a short little JSFiddle to demonstrate label-based and programmatic focus into a card field [here](https://jsfiddle.net/kopuxdc1/).

Hopefully this helps! Feel free to open an issue any time with feedback, questions, or ideas of any kind!

**Comment by chrissrogers** [comment]
I'm closing this for now -- please do feel free to re-open or create a new issue if anything comes to mind. Cheers!
