### ISSUE TITLE
Fix input validations for month and year

### ISSUE THREAD

**Issue by mbesada** [recurly/recurly-js#526]
Hello there, I opted to use separate fields for year and month and I want to add in-field validation messages like 'invalid month' Or 'invalid year' using the onChange event, but seems that recurly.js validates both fields at the same time returning that both fields are valid or both invalid

**Comment by chrissrogers** [comment]
Hi @mbesada! You're absolutely correct that we only validate the expiration data collectively, and not individually. I'd be happy to add this as a feature request.

For validations I'm thinking a logical flow like the following would be best, but please let me know if this doesn't fit your use-case:

1. Given the current date is **November 1, 2019**

| input | month valid? | year valid? | notes |
| ----- | ------------- | ---------- | ------ |
| `11/18` | `false` | `false`| functions as current |
| `01/19` | `false` | `true` | month is valid because there is a month value that can make this valid |
| `13/19` | `false` | `true` | year is valid because there is a month value that can make this valid |
| `12/19` | `true`  | `true` | |
| `12/18` | `true` | `false` | currently both `false` |
| `01/18` | `false` | `false` | currently both `false`  |

**Comment by mbesada** [comment]
Hey @chrissrogers thanks for the fast answer, 
Yes, That should work (assuming that you mean year in the 2nd row instead month :) )
There is also one last case in wich one of the fields is null, it would be nice that the validation returns true as long as the year or month by istelf are valid, ie: null year but month between 1 and 12 or null month with a year >= current
:+1:

**Comment by chrissrogers** [comment]
> There is also one last case in wich one of the fields is null, it would be nice that the validation returns true as long as the year or month by istelf are valid, ie: null year but month between 1 and 12 or null month with a year >= current

Agreed! Good call-out.
