### ISSUE TITLE
Apple pay: wrong arguments to completeShippingMethodSelection

### ISSUE THREAD

**Issue by wcauchois** [recurly/recurly-js#528]
Hi,

On this line https://github.com/recurly/recurly-js/blob/master/lib/recurly/apple-pay.js#L319

The completeShippingMethodSelection method is called with only two arguments. However [as documented here](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778024-completeshippingmethodselection) the first argument should be a status code (in versions 1/2 of the API which I think the Recurly lib is using).

It would be nice to get this fixed.

**Comment by chrissrogers** [comment]
Hi @wcauchois -- excellent, thank you for the great call-out. I'll put in a fix for this right away so that we can get you unblocked.

If you're willing to share any details about your integration needs, we'd be happy to hear them. Recurly dosn't explicitly support shipping address collection with Apple Pay, and we recommend folks collect shipping information separately. If you're listening for Apple Pay shipping address selection on your own, then it's totally possible to collect that shipping info and pass it to the Recurly API on your server separately, but in Recurly.js we do not save shipping address information.

**Comment by chrissrogers** [comment]
I'll suggest the following way to collect shipping information yourself using our `ApplePaySession`

```js
const applePay = recurly.ApplePay(/* opts */);

applePay.on('shippingContactSelected', event => {
  // event.shippingContact (https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypayment/1916097-shippingcontact)
});

// ...

applePay.begin();
```

**Comment by wcauchois** [comment]
@chrissrogers thanks for the prompt response and fix!

That's a good call about the event. It feels a bit hacky to keep track of the shipping method via that event though (although it would be the appropriate place to update pricing). I think the source-of-truth for the shipping info would be the shippingContact field on [ApplePayPayment](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypayment). It would be cool if your library would expose this to us -- perhaps by firing an event on onPaymentAuthorized which I don't think is currently done.

Another thing I've run into -- on the subject of onShippingContactSelected, I think that is the place where you're supposed to update taxes based on shipping address, and then call completeShippingContactSelection with updated line items. However the only hook your library provides into that is via a synchronously-run event and Pricing can happen asynchronously (PricingPromise etc).  It'd be nice if there was a callback-based hook for clients of this library, so the hook could get executed and they could call some callback to indicate they've finished updating their pricing.

Hopefully those suggestions are helpful. Thanks again for your work on this library!

**Comment by chrissrogers** [comment]
Totally agreed. I can add an event to `onPaymentAuthorized` right now to help on that front.

On the overall subject of shipping contacts and methods though, it comes back to our shipping support in ApplePay for now: we recommend calculating tax estimates with `Pricing`, which will take taxes into account, and recommend for accuracy and ease of integration to collect shipping info outside of the Apple Pay dialogue. For instance, `Pricing` will update the tax fed to the Apple Pay dialogue according to the shipping address that `Pricing` understands, but the shipping address in `Pricing` will not update according to selections made in the Apple Pay dialogue. I'd say that once we make the move to more tightly support shipping information provided by Apple Pay, then we'll be performing those two-way syncs -- but for now it is written to be one-way. Since it seems your integration is skewing to a more advanced state, then I can totally understand wanting to hook in in this manner.

Thank you very much for the suggestions! I have logged them in the realm of feature requests and we'll address them as we evolve our Apple Pay shipping support. As ever, feel obliged to create issues for any suggestions or questions you have.

**Comment by chrissrogers** [comment]
This was closed with the fix being merged. This will go into the next version, currently slated as `v4.10.0`. I don't have a precise timeline for when we will release that version on CI, but I will update here as soon as it is. cheers!
