### ISSUE TITLE
Fix risk.ThreeDSecure test case rendering

### ISSUE THREAD

**Issue by openinformation** [recurly/recurly-js#534]
## Why
The 3DS challenge test strategy renders an iFrame in a dynamically created container div. Since the div has no dimensions, it is too small to display the full iFrame and it appears cut-off:

![Screenshot 2019-07-31 at 17 40 47](https://user-images.githubusercontent.com/1410958/62229361-ca8eea80-b3bf-11e9-844d-0b06d43e1e3b.png)

This makes testing uncecessary hard:

## How

When creating the recurly Frame, set the container's dimensions to the Frame's dimension.

**Comment by chrissrogers** [comment]
hi @openinformation !

First, thank you for the report and detail, especially for including a screenshot.

With the 3D Secure challenge flow container, we wanted to allow a degree of flexibility in sizing so that folks could implement the flow without having the size mandated. Since the container is actually a cross-domain iframe whose contents will ultimately be controlled by the customer's bank, there is no reliable way to auto-size the container.

By default, the iframe will expand its height to the height of its container. So if the element you target to place the challenge has a height of `400px`, that is the height that the iframe will expand to.

So in this example:

```html
<div id="my-authentication-container" class="container-3ds-authentication"></div>
```

```css
.container-3ds-authentication {
  width: 250px;
  height: 400px;
}
```

```js
const risk = recurly.Risk();
const threeDSecure = risk.ThreeDSecure({ actionTokenId: 'ABCDEFGHIJKL012345' });
threeDSecure.attach(document.querySelector('#my-authentication-container'));
```

The challenge flow iframe and its dynamically-generated container will expand to the height of `400px`.

We'd be happy to consider providing a default style in `recurly.css` as well, and will be updating our documentation to better illustrate how the challenge sizing operates.

Hopefully this helps in some way. Please do let me know!

**Comment by openinformation** [comment]
Hi @chrissrogers, thanks for the fast reply.

I did set `height` and `width` for my wrapper container, but the conainer created by recurly.js `<div data-recurly="three-d-secure-container">"` has no dimension, which seems to cause the problem.

My wrapper div with dimensions, the dynamically generated div without:
![Screenshot 2019-08-01 at 16 53 06](https://user-images.githubusercontent.com/1410958/62304151-b4476400-b47d-11e9-923e-8a8008232ce5.png)

My wrapper div AND the dynamically generated div with dimensions:
![Screenshot 2019-08-01 at 16 54 28](https://user-images.githubusercontent.com/1410958/62304218-d9d46d80-b47d-11e9-98e4-7022fb21dc29.png)

Seems to me that simply adding `100%` for  `height` and `width` for the div wrapped around the recurly Frame would resolve this?

**Comment by openinformation** [comment]
@chrissrogers thx!

**Comment by vojtech-dobes** [comment]
@chrissrogers Is it correct that 4.10.1 is pre-release? There at least seems to be mismatch between tag and name of the pre-release :). Non-pre-release would be great.

<img width="212" alt="Snímek obrazovky 2019-09-03 v 11 13 17" src="https://user-images.githubusercontent.com/415925/64160263-f9273780-ce3b-11e9-81c6-45b97d8a7124.png">

**Comment by chrissrogers** [comment]
@vojtech-dobes Thanks for catching that -- the name of the pre-release was incorrect, and the tag itself is correct. I'll post here as soon as it's been released to CDN.
