### ISSUE TITLE
Promise Rejected - hosted-field.js

### ISSUE THREAD

**Issue by patrickghidossi** [recurly/recurly-js#604]
![paused_on_promise_rejection](https://user-images.githubusercontent.com/20171803/81014759-b7abb980-8e1a-11ea-8ccc-5409af868566.png)

We're integrating with Recurly to handle the billing of our users, and on our registration form built in Angular we're making use of the Recurly card input. 

With Dev Tools → Sources → Pause on Exception turned on, on load of our registration page the debugger pauses on the exception shown in the screenshot. It appears that a promise was rejected within the hosted-field.js file.

This may be the result of an incorrect implementation on our part, but all of the actual functionality works as expected.

Our line of HTML:
`<div data-recurly="card" id="recurly_card_info"></div>`

**Comment by chrissrogers** [comment]
This looks like it may just be due to your debugger being set to pause on exceptions. If you disable that capability or resume execution from that point, is an error message propagated to the console? Through the normal course of execution, a promise may reject in an expected manner, but this scenario is usually caused by a synchronous promise rejection that lacks a final explicit handler.

If you have the ability to reproduce this on codesandbox, I'd be happy to have a deeper look! While the error isn't a concern with runtime, nor will it cause a user-visible issue, I'd like to pinpoint where the issue is in order to clean it up.
