### ISSUE TITLE
Is there a way to configure inputs to remove Chrome's autofill styles? 

### ISSUE THREAD

**Issue by luanadeoliveira** [recurly/recurly-js#659]
I searched everywhere to see if there is a way to remove the Chrome's webkit autofill styles? I know there is a way with CSS for example: `input:-webkit-autofill { -webkit-box-shadow: 0 0 0px 1000px #ffffff inset !important; }` 

but this doesn't effect the input fields that are nested in the iframe. 

Are there style properties that I can use to customize and remove the autofill?

**Comment by chrissrogers** [comment]
We don't currently support this style declaration being passed in, and this is something we would need to implement on one of our libraries that runs inside of the Element iframe, so I can take this as a feature request!

I'll close this issue for now since we'll track the feature request internally, but will provide any updates here in this issue.

Thanks, this is a good idea.

**Comment by avivshafir** [comment]
@chrissrogers I'm also facing this issue, this can be quite important for us, as we use dark theme and the chrome's autofill is making the input style white inside, see attached image

<img width="575" alt="Screen Shot 2021-05-09 at 14 00 11" src="https://user-images.githubusercontent.com/6135443/117569612-2aefa780-b0cf-11eb-9be8-c2cfba926bef.png">

Is there a way to follow on this feature request progress?
Is there any way we can make It work in the meantime?

Thanks!

**Comment by avivshafir** [comment]
@chrissrogers ?
