### ISSUE TITLE
IE11 issue using recurly from CDN (no issue when building from source)

### ISSUE THREAD

**Issue by robinchesterman** [recurly/recurly-js#663]
We are experiencing an issue with recurly in IE11:

```
Unable to get property 'bind' of undefined or null reference
```

This appears to come from the constructor of `bus.js`: `this.receive = this.receive.bind(this);`

However, what is interesting is that we only have the issue using the recurly CDN (https://js.recurly.com/v4/recurly.js)

When we tried building recurly from source and using the output, there was no issue at all. We tested this using v4.15.1, v.4.15.0 and v.4.14.0 - all are fine.

When diffing the built output with what is served from the CDN, there are discrepancies, although it isn't easy to see where they come from.

The homepage of the GitHub repo says that v4.15.0 is the latest release and v4.15.1 is pre-release, although the CDN version includes a "4.15.1" string.  Both versions build from source have diffs when compared to the CDN.

Can you suggest anything in the recurly deployment process that would cause a different output? I tested it using the webpack and webpack-cli versions defined in the package.json as well as the latest versions.

**Comment by chrissrogers** [comment]
Hi @robinchesterman happy to see if we can get to the bottom of this.

Our tests show no similar error in IE11 (11.0.9600.19572 -- Windows 7), so I think we'll need some assistance in determining a way to reproduce the problem. We'll need:

- Exact version of Windows and IE11, down to the patch version
- Whether this occurs on a barebones example use of Recurly.js, like those found in https://github.com/recurly/recurly-integration-examples
- If possible, an example in CodeSandbox that can reproduce this error

Anything from above will be super helpful in helping me to track down the problem.

> When diffing the built output with what is served from the CDN, there are discrepancies, although it isn't easy to see where they come from.

This isn't too terribly surprising since the build tools and environment may differ slightly from our CI control. I'd be curious to see a diff if you have one, though. Especially if it centered around `bind` calls.

Thanks for noting the release page discrepancy as well. It's been updated to reflect `v4.15.1` being the latest release.

Cheers and happy new year to you!
